# Generated by Django 4.2.1 on 2023-06-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Dubai', max_length=255),
            preserve_default=False,
        ),
    ]
