# Generated by Django 4.2.1 on 2023-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_profile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
