# Generated by Django 4.2.1 on 2023-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_first_name_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
